# Generated by Django 6.0.2 on 2026-02-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. documents, health, training, legal, safety, finance', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='community',
            name='community_type',
            field=models.CharField(blank=True, help_text='e.g. welfare, nrna, community, legal, religious, professional', max_length=50),
        ),
        migrations.AddField(
            model_name='community',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='community',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='embassy',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='embassy',
            name='labor_attache',
            field=models.CharField(blank=True, help_text='Alias for template', max_length=150),
        ),
    ]
