# Generated by Django 5.2.6 on 2026-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_checklistitem_category_community_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='icon',
            field=models.CharField(default='description', help_text='Material Icons name', max_length=50),
        ),
    ]
